1.Split the string

In [ ]:
string = "hai there sam"
words = string.split(',')
print(words)

['hai there sam']


2. Use the format() to print the string


In [ ]:
planet="earth"
diameter="12742"
print('The diameter of {} is {} kilometers'.format(planet, diameter));

The diameter of earth is 12742 kilometers


3. In this nest dictionary grab the word "hello"

In [ ]:
d={'k1' :[1,2,3,{'tricky' :['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello


4.1. Create an array of 10 zeros

In [ ]:
import numpy as np
arr = np.zeros(10)
print("Array of 10 zeros")
print(arr)

Array of 10 zeros
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4.2. Create an array of 10 fives

In [ ]:
import numpy as np
arr = np.ones(10)*5
print("Array og 10 fives")
print(arr)

Array og 10 fives
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


5. Create an array of all even integer from 20 to 35

In [ ]:
import numpy as np
arr = np.arange(20,35,2)
print("Array of all even numbers from 20 to 35")
print(arr)

Array of all even numbers from 20 to 35
[20 22 24 26 28 30 32 34]


6.Create a 3*3 matrix with ranging from 0 to 8

In [ ]:

import numpy as np
X=np.arange(0,9).reshape(3,3)
print(X)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7. concatenation

In [ ]:
import numpy as np
a=np.array([1,2,3])
print(a)
b=np.array([4,5,6])
print(b)
print('concate of a & b')
print(np.concatenate((a,b)))

[1 2 3]
[4 5 6]
concate of a & b


TypeError: ignored

8. create a dataframe

In [ ]:
import pandas as pd
pd.DataFrame({0:[1]*3,1:[1]*3})

0  1
0  1  1
1  1  1
2  1  1

9. Generate the date series

In [ ]:
import datetime
import pandas as pd
test_date = datetime.datetime.strptime("01-01-2023", "%d-%m-%y")
periods = datetime.datetime.strptime("02-02-2023", "%d-%m-%y")
date_generted = pd.date_range(test_date, periods)
print(date_generated.strptime("%d-%m-%y"))

ValueError: ignored

10. create 2d dataframe


In [ ]:
import pandas as pd

lists =[[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc',24]]

df=pd.DataFrame(lists, columns=['ID','Name', 'Age'])
print(df)

   ID Name  Age
0   1  aaa   22
1   2  bbb   25
2   3  ccc   24
